language: scala
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
scala:
- 2.10.4
jdk:
- oraclejdk8
script: sbt ++${TRAVIS_SCALA_VERSION} test
deploy:
  on:
    branch: master
  provider: heroku
  app: nescala
  api_key:
    secure: vAQtzZseSt0/2eXXT55sjBO2G3waUo+56GEKS+nD6o3zPUpEMk7h06zg3nSaCq0kelGCQvTTp6BnmfeLc4rG0YiUxZdeQTYe+fqaoc/yZwqKHTkO4o8awBJAY6L6LdMBKewDBehhub4bEpzEL4feYXUtpd86/Cx769GUcxxs4/1sLIt9pCm6ERhcRJZuf733og9t/wDctzzs7z/ib0a335Dda5mUhh1yfiyMwt/l+8Jrp73cmhPnN/dDcvKGnubN6CuAraZlPlkK30ZymacLluFtnOlblVHmJbuj8sS/3rxELG/PS4vVhjTcmgYtYa7NgDXoYwb++euVbJ6vbxopvI0WUiLYQQLiv8acpikMQJ9obGtMhmXZbn+QLQUhEK5rUixb5nPPHyBhkclANch6CPC1eQUvTJchejRbGTB3/H/v1tqzA/LSFisiP7tfJrgCmEu0CDOfatzWIQSsyoKHvPmCT29U63nUCA5wOv0IReABHkx/mKgWescVbdCjUZgjfveaYjt+LeMhz7BN65PmquGrB58+XHRmOiAMpnmz0258biy0656QCCq64cvB9IYqvrduxfIhSyRalPUJZu73RP7wAm51NpyI742jRCC1TihijeLYmsKO0hFIc9osiavIDz55bZ2wsGsX/BWLVWLXTofPwPdiM42SSrSBBuitOIQ=
