language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
scala:
  - 2.10.4
jdk: # https://devcenter.heroku.com/articles/java-support#supported-java-versions
  - oraclejdk7
  - oraclejdk8
script: sbt ++${TRAVIS_SCALA_VERSION} test
